interface ZIF_BC_DDL_REQUEST_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZBC_DDL_REQUEST,
 CREATE_ZBC_DDL_REQUEST         TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE7A6C2',
 DELETE_ZBC_DDL_REQUEST         TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE826C2',
 LOCK_ZBC_DDL_REQUEST           TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE6E6C2',
 SAVE_ZBC_DDL_REQUEST           TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE8A6C2',
 UNLOCK_ZBC_DDL_REQUEST         TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE726C2',
 UPDATE_ZBC_DDL_REQUEST         TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE7E6C2',
 VALIDATE_ZBC_DDL_REQUEST       TYPE /BOBF/ACT_KEY VALUE '06789A0505941EE9AEBC197BFBE866C2',
      END OF ZBC_DDL_REQUEST,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZBC_DDL_REQUEST,
        BEGIN OF LOCK_ZBC_DDL_REQUEST,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZBC_DDL_REQUEST,
        BEGIN OF UNLOCK_ZBC_DDL_REQUEST,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZBC_DDL_REQUEST,
      END OF ZBC_DDL_REQUEST,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZBC_DDL_REQUEST,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '06789A0505941EE9AEBC197BFBE986C2',
      END OF ZBC_DDL_REQUEST,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZBC_DDL_REQUEST,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE6C6C2',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE686C2',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE786C2',
      END OF ZBC_DDL_REQUEST,
      BEGIN OF ZBC_DDL_REQUEST_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE906C2',
      END OF ZBC_DDL_REQUEST_LOCK,
      BEGIN OF ZBC_DDL_REQUEST_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE8E6C2',
      END OF ZBC_DDL_REQUEST_MESSAGE,
      BEGIN OF ZBC_DDL_REQUEST_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '06789A0505941EE9AEBC197BFBE926C2',
      END OF ZBC_DDL_REQUEST_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZBC_DDL_REQUEST,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZBC_DDL_REQUEST,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '06789A0505941EE9AEBC197BFBE5E6C2' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBC_DDL_REQUEST' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZBC_DDL_REQUEST,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '06789A0505941EE9AEBC197BFBE9A6C2',
 NEW_REQUEST                    TYPE /BOBF/DET_KEY VALUE '06789A0505941EE9AEBC3AE6FCA34702',
      END OF ZBC_DDL_REQUEST,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZBC_DDL_REQUEST                TYPE /BOBF/OBM_GROUP_KEY VALUE '06789A0505941EE9AEBE0EE0E04A09F2',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZBC_DDL_REQUEST                TYPE /BOBF/OBM_NODE_KEY VALUE '06789A0505941EE9AEBC197BFBE626C2',
 ZBC_DDL_REQUEST_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '06789A0505941EE9AEBC197BFBE6A6C2',
 ZBC_DDL_REQUEST_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '06789A0505941EE9AEBC197BFBE666C2',
 ZBC_DDL_REQUEST_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '06789A0505941EE9AEBC197BFBE766C2',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZBC_DDL_REQUEST,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_REQUEST                     TYPE STRING VALUE 'ID_REQUEST',
  ERDAT                          TYPE STRING VALUE 'ERDAT',
  ERZET                          TYPE STRING VALUE 'ERZET',
  ERNAM                          TYPE STRING VALUE 'ERNAM',
  DATA                           TYPE STRING VALUE 'DATA',
      END OF ZBC_DDL_REQUEST,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZBC_DDL_REQUEST,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '06789A0505941EE9AEBC197BFBE646C2',
      END OF ZBC_DDL_REQUEST,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ZBC_DDL_REQUEST,
 GET_REQUEST                    TYPE /BOBF/OBM_QUERY_KEY VALUE '06789A0505941ED9AED508CD53D8EEDA',
      END OF ZBC_DDL_REQUEST,
    END OF SC_QUERY .
  constants:
    BEGIN OF SC_QUERY_RESULT_TYPE_ATTRIBUTE,
      BEGIN OF ZBC_DDL_REQUEST,
        BEGIN OF GET_REQUEST,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 ID_REQUEST                     TYPE STRING VALUE 'ID_REQUEST',
 ERDAT                          TYPE STRING VALUE 'ERDAT',
 ERZET                          TYPE STRING VALUE 'ERZET',
 ERNAM                          TYPE STRING VALUE 'ERNAM',
 DATA                           TYPE STRING VALUE 'DATA',
        END OF GET_REQUEST,
      END OF ZBC_DDL_REQUEST,
    END OF SC_QUERY_RESULT_TYPE_ATTRIBUTE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZBC_DDL_REQUEST,
 NEW_REQUEST                    TYPE /BOBF/VAL_KEY VALUE '06789A0505941EE9AEBE0EE0E049A9F2',
      END OF ZBC_DDL_REQUEST,
    END OF SC_VALIDATION .
endinterface.
